# Generated by Django 4.2.1 on 2023-05-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
