# Generated by Django 4.2.1 on 2023-05-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_productos_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='oferta',
        ),
        migrations.AddField(
            model_name='productos',
            name='precio_final',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
