# Generated by Django 4.2.1 on 2023-05-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_remove_productos_precio_usd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='precio_final',
        ),
        migrations.AddField(
            model_name='productos',
            name='oferta',
            field=models.IntegerField(default=0),
        ),
    ]
