# Generated by Django 4.2.1 on 2023-05-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_remove_productos_precio_final_productos_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precio_final',
            field=models.IntegerField(default=0),
        ),
    ]
