# Generated by Django 4.2.1 on 2023-05-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_productos_precio_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='oferta',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='precio_final',
        ),
    ]
