# Generated by Django 4.2.1 on 2023-05-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_remove_productos_oferta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='oferta',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
