# Generated by Django 4.2.1 on 2023-05-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_productos_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precio_final',
            field=models.IntegerField(null=True),
        ),
    ]
