# Generated by Django 4.2.1 on 2023-05-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_productos_precio_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio_final',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
