# Generated by Django 4.2.1 on 2023-05-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_alter_productos_precio_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precio_usd',
            field=models.IntegerField(null=True),
        ),
    ]
