# Generated by Django 4.2.1 on 2023-06-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_productos_precio_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=5)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
    ]
