# Generated by Django 4.0 on 2023-06-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
