# Generated by Django 3.2 on 2023-06-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
