# Generated by Django 4.0 on 2023-06-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_alter_productos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='imagen',
            field=models.ImageField(upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(upload_to='fotos'),
        ),
    ]
